"""init

Revision ID: 653ec536891b
Revises: 
Create Date: 2026-02-04 05:15:31.863348
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653ec536891b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('default_currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CLOSED', name='walletstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('wallet_id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('bank_account',
    sa.Column('bank_account_id', sa.String(), nullable=False),
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('masked_details', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('bank_account_id')
    )
    op.create_table('wallet_account',
    sa.Column('wallet_account_id', sa.String(), nullable=False),
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('wallet_account_id')
    )
    op.create_index('uq_wallet_currency', 'wallet_account', ['wallet_id', 'currency'], unique=True)
    op.create_table('wallet_hold',
    sa.Column('hold_id', sa.String(), nullable=False),
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RELEASED', 'CONSUMED', name='holdstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('related_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('hold_id')
    )
    op.create_table('wallet_transaction',
    sa.Column('tx_id', sa.String(), nullable=False),
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('TOPUP_BANK', 'WITHDRAWAL', 'FEE', 'ADJUSTMENT', name='txtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='txstatus'), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('counterparty', sa.String(), nullable=True),
    sa.Column('searchable_text', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('tx_id')
    )
    op.create_index('idx_tx_filters', 'wallet_transaction', ['wallet_id', 'currency', 'type', 'status', 'occurred_at'], unique=False)
    op.create_index('idx_tx_wallet_time', 'wallet_transaction', ['wallet_id', 'occurred_at'], unique=False)
    op.create_table('withdrawal',
    sa.Column('withdrawal_id', sa.String(), nullable=False),
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('bank_account_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'SUBMITTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', 'REVERSED', 'MANUAL_REVIEW', name='withdrawalstatus'), nullable=False),
    sa.Column('hub_reference', sa.String(), nullable=True),
    sa.Column('hold_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.bank_account_id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('withdrawal_id')
    )
    op.create_index('idx_withdrawal_wallet_time', 'withdrawal', ['wallet_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_withdrawal_wallet_time', table_name='withdrawal')
    op.drop_table('withdrawal')
    op.drop_index('idx_tx_wallet_time', table_name='wallet_transaction')
    op.drop_index('idx_tx_filters', table_name='wallet_transaction')
    op.drop_table('wallet_transaction')
    op.drop_table('wallet_hold')
    op.drop_index('uq_wallet_currency', table_name='wallet_account')
    op.drop_table('wallet_account')
    op.drop_table('bank_account')
    op.drop_table('wallet')
    # ### end Alembic commands ###
