"""add_ledger_posting

Revision ID: 755fd379780f
Revises: dc55cab31e7d
Create Date: 2026-02-12 02:25:45.611197
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '755fd379780f'
down_revision = 'dc55cab31e7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_posting', sa.Column('ledger_posting_id', sa.String(), nullable=False))
    op.add_column('ledger_posting', sa.Column('request_json', sa.Text(), nullable=True))
    op.add_column('ledger_posting', sa.Column('response_json', sa.Text(), nullable=True))
    op.alter_column('ledger_posting', 'provider',
               existing_type=postgresql.ENUM('FINERACT', name='ledgerprovider'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('idx_ledger_posting_provider_ref', table_name='ledger_posting')
    op.drop_index('idx_ledger_posting_wallet_tx', table_name='ledger_posting')
    op.drop_index('uq_ledger_posting_provider_wallet_tx', table_name='ledger_posting')
    op.create_index('idx_ledger_posting_status', 'ledger_posting', ['status', 'created_at'], unique=False)
    op.create_unique_constraint(None, 'ledger_posting', ['wallet_tx_id'])
    op.drop_column('ledger_posting', 'posting_id')
    op.drop_column('ledger_posting', 'request_ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_posting', sa.Column('request_ref', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ledger_posting', sa.Column('posting_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ledger_posting', type_='unique')
    op.drop_index('idx_ledger_posting_status', table_name='ledger_posting')
    op.create_index('uq_ledger_posting_provider_wallet_tx', 'ledger_posting', ['provider', 'wallet_tx_id'], unique=True)
    op.create_index('idx_ledger_posting_wallet_tx', 'ledger_posting', ['wallet_tx_id'], unique=False)
    op.create_index('idx_ledger_posting_provider_ref', 'ledger_posting', ['provider_ref'], unique=False)
    op.alter_column('ledger_posting', 'provider',
               existing_type=sa.String(),
               type_=postgresql.ENUM('FINERACT', name='ledgerprovider'),
               existing_nullable=False)
    op.drop_column('ledger_posting', 'response_json')
    op.drop_column('ledger_posting', 'request_json')
    op.drop_column('ledger_posting', 'ledger_posting_id')
    # ### end Alembic commands ###
