"""ledger_posting

Revision ID: dc55cab31e7d
Revises: 653ec536891b
Create Date: 2026-02-10 23:55:45.285750
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc55cab31e7d'
down_revision = '653ec536891b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_posting',
    sa.Column('posting_id', sa.String(), nullable=False),
    sa.Column('wallet_tx_id', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('FINERACT', name='ledgerprovider'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'POSTED', 'FAILED', name='ledgerpostingstatus'), nullable=False),
    sa.Column('provider_ref', sa.String(), nullable=True),
    sa.Column('request_ref', sa.String(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_tx_id'], ['wallet_transaction.tx_id'], ),
    sa.PrimaryKeyConstraint('posting_id')
    )
    op.create_index('idx_ledger_posting_provider_ref', 'ledger_posting', ['provider_ref'], unique=False)
    op.create_index('idx_ledger_posting_wallet_tx', 'ledger_posting', ['wallet_tx_id'], unique=False)
    op.create_index('uq_ledger_posting_provider_wallet_tx', 'ledger_posting', ['provider', 'wallet_tx_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ledger_posting_provider_wallet_tx', table_name='ledger_posting')
    op.drop_index('idx_ledger_posting_wallet_tx', table_name='ledger_posting')
    op.drop_index('idx_ledger_posting_provider_ref', table_name='ledger_posting')
    op.drop_table('ledger_posting')
    # ### end Alembic commands ###
